#!/bin/bash

if [[ $# -ne 1 ]] ; then
	echo "Description: remove single file from SRM."
	echo "Usage: srm_dir_name"
	exit
fi

FILE_NAME="$1"
REMOTE_DIR="$1"

srmrm -2 "srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/$FILE_NAME"
